package com.thesomeshkumar.flixplorer.ui.theme

import androidx.compose.ui.graphics.Color

val flix_color_light_primary = Color(0xFF385BA9)
val flix_color_light_onPrimary = Color(0xFFFFFFFF)
val flix_color_light_primaryContainer = Color(0xFFD9E2FF)
val flix_color_light_onPrimaryContainer = Color(0xFF001946)
val flix_color_light_secondary = Color(0xFF585E71)
val flix_color_light_onSecondary = Color(0xFFFFFFFF)
val flix_color_light_secondaryContainer = Color(0xFFDCE2F9)
val flix_color_light_onSecondaryContainer = Color(0xFF151B2C)
val flix_color_light_tertiary = Color(0xFF725572)
val flix_color_light_onTertiary = Color(0xFFFFFFFF)
val flix_color_light_tertiaryContainer = Color(0xFFFDD7FA)
val flix_color_light_onTertiaryContainer = Color(0xFF2A122C)
val flix_color_light_error = Color(0xFFBA1A1A)
val flix_color_light_errorContainer = Color(0xFFFFDAD6)
val flix_color_light_onError = Color(0xFFFFFFFF)
val flix_color_light_onErrorContainer = Color(0xFF410002)
val flix_color_light_background = Color(0xFFFEFBFF)
val flix_color_light_onBackground = Color(0xFF1B1B1F)
val flix_color_light_surface = Color(0xFFFEFBFF)
val flix_color_light_onSurface = Color(0xFF1B1B1F)
val flix_color_light_surfaceVariant = Color(0xFFE1E2EC)
val flix_color_light_onSurfaceVariant = Color(0xFF44464F)
val flix_color_light_outline = Color(0xFF757780)
val flix_color_light_inverseOnSurface = Color(0xFFF2F0F4)
val flix_color_light_inverseSurface = Color(0xFF303034)
val flix_color_light_inversePrimary = Color(0xFFB1C6FF)
val flix_color_light_shadow = Color(0xFF000000)
val flix_color_light_surfaceTint = Color(0xFF385BA9)
val flix_color_light_outlineVariant = Color(0xFFC5C6D0)
val flix_color_light_scrim = Color(0xFF000000)

val flix_color_dark_primary = Color(0xFFB1C6FF)
val flix_color_dark_onPrimary = Color(0xFF002C70)
val flix_color_dark_primaryContainer = Color(0xFF1B438F)
val flix_color_dark_onPrimaryContainer = Color(0xFFD9E2FF)
val flix_color_dark_secondary = Color(0xFFC0C6DC)
val flix_color_dark_onSecondary = Color(0xFF2A3042)
val flix_color_dark_secondaryContainer = Color(0xFF404659)
val flix_color_dark_onSecondaryContainer = Color(0xFFDCE2F9)
val flix_color_dark_tertiary = Color(0xFFE0BBDD)
val flix_color_dark_onTertiary = Color(0xFF412742)
val flix_color_dark_tertiaryContainer = Color(0xFF593D59)
val flix_color_dark_onTertiaryContainer = Color(0xFFFDD7FA)
val flix_color_dark_error = Color(0xFFFFB4AB)
val flix_color_dark_errorContainer = Color(0xFF93000A)
val flix_color_dark_onError = Color(0xFF690005)
val flix_color_dark_onErrorContainer = Color(0xFFFFDAD6)
val flix_color_dark_background = Color(0xFF1B1B1F)
val flix_color_dark_onBackground = Color(0xFFE3E2E6)
val flix_color_dark_surface = Color(0xFF1B1B1F)
val flix_color_dark_onSurface = Color(0xFFE3E2E6)
val flix_color_dark_surfaceVariant = Color(0xFF44464F)
val flix_color_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val flix_color_dark_outline = Color(0xFF8F9099)
val flix_color_dark_inverseOnSurface = Color(0xFF1B1B1F)
val flix_color_dark_inverseSurface = Color(0xFFE3E2E6)
val flix_color_dark_inversePrimary = Color(0xFF385BA9)
val flix_color_dark_shadow = Color(0xFF000000)
val flix_color_dark_surfaceTint = Color(0xFFB1C6FF)
val flix_color_dark_outlineVariant = Color(0xFF44464F)
val flix_color_dark_scrim = Color(0xFF000000)

val flix_color_translucent_black = Color(0xE6000000)

val seed = Color(0xFF273047)
